building_graph:
  ncpus: 100
  max_input_hgt: 100
  preprocessed_image_width: 500
  preprocessed_image_height: 60
  resizing_factor: 0.5
  padding: 8

training:
  wandb: False
  seed: 42
  clip: 1
  ddp: True
  gpus: 0,1
  world_size: 2
  epochs: 50
  batch_size: 20
  learning_rate: 0.0001
  weight_decay: 0.00001
  betas: [0.9, 0.8]
  early_stopping: 5
  scheduler_step_size: 50
  scheduler_gamma: 0.5
  load_trained_model_for_testing: False

preprocessing:
  path_to_data: "/home/gauravs/data/grenc_trdec"
  markup: "mml"
  vocab_freq: 5
  device: "cuda"
  shuffle: True
  num_workers: 0
  pin_memory: False

model:
  isGraphPixel: False
  isVitPixel: False

  graph_model:
    input_channels: 3
    hid_dim: 64
    dropout: 0.1

  vit:
    patch_size: 20
    pixel_patch_size: 4
    nheads: 8
    emb_dim: 128
    depth: 4
    mlp_ratio: 4
    qkv_bias: True
  
  decoder_transformer:
    emb_dim: 256
    dec_hid_dim: 512
    nheads: 4
    max_len: 350
    n_xfmer_decoder_layers: 4
    dim_feedfwd: 1024