building_graph:
  ncpus: 100
  max_input_hgt: 100
  preprocessed_image_width: 500
  preprocessed_image_height: 60
  resizing_factor: 0.5
  padding: 8

training:
  wandb: False
  seed: 42
  clip: 1
  ddp: True
  gpus: 0,1
  world_size: 2
  epochs: 50
  batch_size: 20
  clip_learning_rate: 0.0001
  clip_betas: [0.9, 0.9]
  clip_weight_decay: 0.000001
  dec_learning_rate: 0.0001
  dec_weight_decay: 0.00001
  dec_betas: [0.9, 0.8]
  early_stopping: 3
  scheduler_step_size: 50
  scheduler_gamma: 0.5
  load_trained_model_for_testing: False

preprocessing:
  path_to_data: "/home/gauravs/data/grenc_trdec"
  markup: "mml"
  vocab_freq: 5
  device: "cuda"
  shuffle: True
  num_workers: 0
  pin_memory: False

model:
  dropout: 0.2
  projection_dim: 256
  temperature: 1.0

  cnn:
    input_channels: 3
    hid_dim: 256

  xfmer_enc:
    emb_dim: 256
    hid_dim: 512
    max_len: 350
    nheads: 4
    n_xfmer_encoder_layers: 6
    dim_feedfwd: 1024
  
  xfmer_dec:
    emb_dim: 256
    hid_dim: 512
    nheads: 4
    n_xfmer_decoder_layers: 4
    dim_feedfwd: 1024